// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisableButtonController from "./disable_button_controller"
application.register("disable-button", DisableButtonController)

import FakeDropdownController from "./fake_dropdown_controller"
application.register("fake-dropdown", FakeDropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarActiveTabController from "./navbar_active_tab_controller"
application.register("navbar-active-tab", NavbarActiveTabController)
