// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import DisableButtonController from "./disable_button_controller"
application.register("disable-button", DisableButtonController)

import FakeDropdownController from "./fake_dropdown_controller"
application.register("fake-dropdown", FakeDropdownController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarActiveTabController from "./navbar_active_tab_controller"
application.register("navbar-active-tab", NavbarActiveTabController)

import PhotoswipeController from "./photoswipe_controller"
application.register("photoswipe", PhotoswipeController)
